<?xml version="1.0"?>
<package format="3">
  <name>smarthome_bringup</name>
  <version>0.1.0</version>
  <description>Top-level launch package for smart-home sorting robot.</description>
  <maintainer email="you@example.com">smarthome team</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>smarthome_comm</exec_depend>
  <exec_depend>smarthome_task_manager</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
